add_library(hatt-electrical STATIC src/Connectivity.cpp src/DcSolver.cpp)
add_library(HattEDA::Electrical ALIAS hatt-electrical)
target_include_directories(hatt-electrical PUBLIC include)
set_target_properties(hatt-electrical PROPERTIES AUTOMOC OFF)
if(MSVC)
    target_compile_options(hatt-electrical PRIVATE /W4 /permissive-)
else()
    target_compile_options(hatt-electrical PRIVATE -Wall -Wextra -Wpedantic)
endif()
