#include "hatt/ui/SketchCircuit.hpp"
#include "hatt/ui/ComponentCatalog.hpp"
#include "hatt/ui/CircuitWorkflow.hpp"
#include "hatt/ui/MainWindow.hpp"
#include "hatt/ui/Theme.hpp"
#include <QDialog>
#include <QDialogButtonBox>
#include <QComboBox>
#include <QDir>
#include <QDoubleSpinBox>
#include <QPushButton>
#include <QPolygonF>
#include <QRegularExpression>
#include <QFontDatabase>
#include <QLabel>
#include <QSettings>
#include <QSpinBox>
#include <QTabWidget>
#include <QTemporaryDir>
#include <QTimer>
#include <QMenu>
#include <QTextEdit>
#include <QToolButton>
#include <QUndoStack>
#include <QtTest>

using namespace hatt::ui;
class SketchCircuitTests : public QObject {
    Q_OBJECT
private slots:
    void initTestCase() {
        if (!qEnvironmentVariable("HATT_SCREENSHOT_DIR").isEmpty()) {
            const QString font = qEnvironmentVariable("SystemRoot") + "/Fonts/segoeui.ttf";
            QVERIFY(QFontDatabase::addApplicationFont(font) >= 0);
        }
        static QTemporaryDir settings;
        QVERIFY(settings.isValid());
        QCoreApplication::setOrganizationName("HattEDA-CircuitTests");
        QCoreApplication::setApplicationName("hatt-sketch-circuit-tests");
        QSettings::setDefaultFormat(QSettings::IniFormat);
        QSettings::setPath(QSettings::IniFormat, QSettings::UserScope, settings.path());
        // New projects are real files; keep them out of the user's Documents folder.
        QSettings().setValue("projects/location", settings.filePath("projects"));
    }
    void dividerSolvesFromActualSymbolPins() {
        const auto document = dcDividerExample();
        const auto snapshot = analyzeSchematic(document);
        QVERIFY2(snapshot.errors.isEmpty(), qPrintable(snapshot.errors.join("; ")));
        QVERIFY(snapshot.simulationErrors.isEmpty());
        QCOMPARE(snapshot.dc.netCount, 3);
        const auto result = hatt::electrical::solveDc(snapshot.dc);
        QVERIFY2(result.success, result.error.c_str());
        QCOMPARE(result.currents.size(), std::size_t(3));
        QVERIFY(std::abs(result.currents[1] - 0.0025) < 1e-10);
        QVERIFY(std::abs(result.currents[2] - 0.0025) < 1e-10);
        QVERIFY(std::abs(result.currents[0] + 0.0025) < 1e-10);
    }
    // Issue #47: schematicWireNets resolves each Wire item to its schematic net name, keyed by
    // item id — a named net (a power rail's label) and an auto-generated one (no terminal/ground
    // touches it, so buildConnectivity names it "N<n>").
    void schematicWireNetsResolveNamedAndAutoGeneratedNets() {
        registerBuiltInCatalog();
        SketchDocument document;
        auto part = [&](const QString& variant, const QString& label, QPointF at) {
            SketchItem item;
            item.kind = SketchItem::Kind::Symbol;
            item.variant = variant;
            item.label = label;
            item.points = {at};
            document << item;
        };
        auto wire = [&](std::initializer_list<QPointF> points) {
            SketchItem item;
            item.kind = SketchItem::Kind::Wire;
            item.points = points;
            document << item;
        };
        part(QStringLiteral("schematic.resistor"), QStringLiteral("R1"), {20.32, 20.32});
        part(QStringLiteral("schematic.resistor"), QStringLiteral("R2"), {40.64, 20.32});
        part(QStringLiteral("schematic.power"), QStringLiteral("VCC"), {15.24, 10.16});
        // R1 pin 1 (15.24, 20.32) to the VCC rail: a named net.
        wire({{15.24, 10.16}, {15.24, 20.32}});
        // R1 pin 2 (25.4, 20.32) to R2 pin 1 (35.56, 20.32): no terminal touches it, so the net
        // gets an auto-generated name.
        wire({{25.4, 20.32}, {35.56, 20.32}});

        const auto snapshot = analyzeSchematic(document);
        QVERIFY2(snapshot.errors.isEmpty(), qPrintable(snapshot.errors.join("; ")));

        const QHash<QString, QString> nets = schematicWireNets(document);
        QCOMPARE(nets.value(document.at(3).id), QStringLiteral("VCC"));
        const QString autoNet = nets.value(document.at(4).id);
        QVERIFY(!autoNet.isEmpty());
        QVERIFY(autoNet != QStringLiteral("VCC"));
        QVERIFY2(autoNet.startsWith(QLatin1Char('N')), qPrintable(autoNet));
    }
    void catalogCurrentSourceSolvesFromSnapshot() {
        registerBuiltInCatalog();
        SketchDocument document;
        auto part = [&](const QString& variant, const QString& label, QPointF at, const QString& value) {
            SketchItem item;
            item.kind = SketchItem::Kind::Symbol;
            item.variant = variant;
            item.label = label;
            item.points = {at};
            item.value = value;
            document << item;
        };
        part(QStringLiteral("catalog.device.idc"), QStringLiteral("I1"), {30, 30}, QStringLiteral("1m"));
        part(QStringLiteral("catalog.device.resistor"), QStringLiteral("R1"), {30, 40}, QStringLiteral("1k"));
        part(QStringLiteral("schematic.ground"), QString(), {20, 35}, QString());
        auto wire = [&](std::initializer_list<QPointF> points) {
            SketchItem item; item.kind = SketchItem::Kind::Wire; item.points = points; document << item;
        };
        wire({{20, 35}, {20, 30}, {24.92, 30}});
        wire({{20, 35}, {20, 40}, {24.92, 40}});
        wire({{35.08, 30}, {40, 30}, {40, 40}, {35.08, 40}});
        const auto snapshot = analyzeSchematic(document);
        QVERIFY2(snapshot.errors.isEmpty(), qPrintable(snapshot.errors.join("; ")));
        QVERIFY2(snapshot.simulationErrors.isEmpty(), qPrintable(snapshot.simulationErrors.join("; ")));
        const auto result = hatt::electrical::solveDc(snapshot.dc);
        QVERIFY2(result.success, result.error.c_str());
        QVERIFY(std::abs(result.voltages[1] - 1.0) < 1e-10);
    }
    void parallelResistorsWithoutGroundAndProbeSolve() {
        registerBuiltInCatalog();
        SketchDocument document;
        auto part = [&](const QString& variant, const QString& label, QPointF at, const QString& value = {}) {
            SketchItem item;
            item.kind = SketchItem::Kind::Symbol;
            item.variant = variant;
            item.label = label;
            item.points = {at};
            item.value = value;
            document << item;
        };
        auto wire = [&](std::initializer_list<QPointF> points) {
            SketchItem item;
            item.kind = SketchItem::Kind::Wire;
            item.points = points;
            document << item;
        };

        part(QStringLiteral("catalog.device.vdc"), QStringLiteral("V1"), {20, 30}, QStringLiteral("5"));
        part(QStringLiteral("catalog.device.resistor"), QStringLiteral("R1"), {45, 20}, QStringLiteral("1k"));
        part(QStringLiteral("catalog.device.resistor"), QStringLiteral("R2"), {45, 30}, QStringLiteral("1k"));
        part(QStringLiteral("catalog.device.resistor"), QStringLiteral("R3"), {45, 40}, QStringLiteral("1k"));
        part(QStringLiteral("schematic.voltage-probe"), QStringLiteral("VP1"), {30, 20});

        // V1 pin 1 feeds the three left pins; all right pins return to V1 pin 2. As in
        // Proteus, this closed circuit does not require a separate Ground symbol.
        wire({{20, 24.92}, {30, 24.92}, {30, 20}, {39.92, 20}});
        wire({{30, 24.92}, {30, 30}, {39.92, 30}});
        wire({{30, 30}, {30, 40}, {39.92, 40}});
        wire({{50.08, 20}, {55, 20}, {55, 50}, {30, 50}});
        wire({{50.08, 30}, {55, 30}});
        wire({{50.08, 40}, {55, 40}});
        wire({{20, 35.08}, {20, 50}, {30, 50}});

        const auto snapshot = analyzeSchematic(document);
        QVERIFY2(snapshot.errors.isEmpty(), qPrintable(snapshot.errors.join("; ")));
        QVERIFY2(snapshot.simulationErrors.isEmpty(), qPrintable(snapshot.simulationErrors.join("; ")));
        const auto result = hatt::electrical::solveDc(snapshot.dc);
        QVERIFY2(result.success, result.error.c_str());
        QCOMPARE(result.currents.size(), std::size_t(4));
        for (int resistor = 1; resistor <= 3; ++resistor)
            QVERIFY(std::abs(result.currents[resistor] - 0.005) < 1e-10);
        QVERIFY(std::abs(result.currents[0] + 0.015) < 1e-10);
        QCOMPARE(snapshot.probes.size(), 1);
        const int probeNet = snapshot.dcNets.indexOf(snapshot.probes.first().net);
        QVERIFY(probeNet >= 0);
        QVERIFY(std::abs(result.voltages[probeNet] - 5.0) < 1e-10);
    }
    void dcUsesSourceNegativeAsImplicitReferenceAndExplainsOpenReturn() {
        auto document = dcDividerExample();
        document.erase(std::remove_if(document.begin(), document.end(), [](const SketchItem& item) {
            return item.variant == QLatin1String("schematic.ground");
        }), document.end());
        auto snapshot = analyzeSchematic(document);
        QVERIFY2(snapshot.simulationErrors.isEmpty(), qPrintable(snapshot.simulationErrors.join("; ")));
        const auto result = hatt::electrical::solveDc(snapshot.dc);
        QVERIFY2(result.success, result.error.c_str());
        QVERIFY(std::abs(result.voltages[snapshot.dc.ground]) < 1e-12);
        const auto source = std::find_if(snapshot.dc.elements.begin(), snapshot.dc.elements.end(),
                                         [](const hatt::electrical::DcElement& element) {
                                             return element.reference == "V1";
                                         });
        QVERIFY(source != snapshot.dc.elements.end());
        QVERIFY(std::abs(result.voltages[source->positive] - 5.0) < 1e-10);

        document = dcDividerExample();
        // Remove the wire that joins V1 pin 2 to the grounded return bus.
        const QPointF sourceReturn{20.32, 35.56};
        document.erase(std::remove_if(document.begin(), document.end(), [&](const SketchItem& item) {
            return item.kind == SketchItem::Kind::Wire && item.points.contains(sourceReturn);
        }), document.end());
        snapshot = analyzeSchematic(document);
        const QString errors = snapshot.simulationErrors.join(' ');
        QVERIFY2(errors.contains("V1 pin 2"), qPrintable(errors));
        QVERIFY(errors.contains("not connected"));
    }
    void transferPreservesPlacementAndRouting() {
        auto schematic = dcDividerExample();
        auto transfer = transferToBoard(schematic, {});
        QVERIFY2(transfer.errors.isEmpty(), qPrintable(transfer.errors.join("; ")));
        QCOMPARE(transfer.added, 3);
        auto board = transfer.document;
        // Footprints are added in designator order; board[1] is linked to schematic[1] (R1).
        const auto r1 = std::find_if(board.begin(), board.end(),
                                     [&](const SketchItem& item) { return item.sourceId == schematic[1].id; });
        QVERIFY(r1 != board.end());
        std::swap(*r1, board[1]);
        translateItem(board[1], {20, 10});
        board[1].quarterTurns = 1;
        const auto guide = boardGuidance(schematic, board);
        QVERIFY2(guide.errors.isEmpty(), qPrintable(guide.errors.join("; ")));
        QCOMPARE(guide.airwires.size(), 3);
        QVERIFY(!guide.airwires[0].net.isEmpty());
        SketchItem track;
        track.kind = SketchItem::Kind::Wire;
        track.points = {guide.airwires[0].line.p1(), guide.airwires[0].line.p2()};
        board.append(track);
        const auto routed = boardGuidance(schematic, board);
        QVERIFY(routed.airwires.size() < guide.airwires.size());
        transfer = transferToBoard(schematic, board);
        QVERIFY(transfer.errors.isEmpty());
        QCOMPARE(transfer.added, 0);
        QCOMPARE(transfer.updated, 0);
        QCOMPARE(transfer.document[1].points, board[1].points);
        QCOMPARE(transfer.document[1].quarterTurns, 1);
        QCOMPARE(transfer.document.last().points, track.points);
        schematic[1].label = "R42";
        transfer = transferToBoard(schematic, board);
        QCOMPARE(transfer.updated, 1);
        QCOMPARE(transfer.document[1].label, QString("R42"));
        schematic[1].pinPadMap = {2, 1};
        transfer = transferToBoard(schematic, board);
        QVERIFY(!transfer.errors.isEmpty());
        QCOMPARE(transfer.document[1].label, board[1].label);
    }
    void rejectsMissingFootprintAndDuplicateLink() {
        auto schematic = dcDividerExample();
        schematic[1].footprint.clear();
        QVERIFY(!transferToBoard(schematic, {}).errors.isEmpty());
        schematic = dcDividerExample();
        auto board = transferToBoard(schematic, {}).document;
        auto duplicate = board.first();
        duplicate.id = "different-id";
        board.append(duplicate);
        QVERIFY(!transferToBoard(schematic, board).errors.isEmpty());
        auto& resistor = schematic[1];
        resistor.value = "NaN";
        QVERIFY(!analyzeSchematic(schematic).simulationErrors.isEmpty());
    }
    void detectsCopperShortAndUnsupportedSimulation() {
        auto schematic = dcDividerExample();
        auto board = transferToBoard(schematic, {}).document;
        const auto& source = board.first();
        const auto* footprint = findSymbol(source.variant);
        SketchItem track;
        track.kind = SketchItem::Kind::Wire;
        track.points = {symbolToWorld(source, footprint->pins[0]), symbolToWorld(source, footprint->pins[1])};
        board.append(track);
        QVERIFY(boardGuidance(schematic, board).errors.join(" ").contains("short"));
        schematic[1].variant = QStringLiteral("schematic.diode");
        QVERIFY(analyzeSchematic(schematic).simulationErrors.join(" ").contains("does not support"));
    }
    // Issue #30 follow-up: boardGuidance only turns a track crossing into a junction when the
    // crossing segments share a copper layer ("Tracks crossing on the same copper layer physically
    // connect; other layers pass over."). Same layer, different schematic nets: a real short. Same
    // geometry split across Top/Bottom copper: not connected, no short.
    void crossingTracksOnDifferentCopperLayersDoNotShort() {
        auto schematic = dcDividerExample();
        auto board = transferToBoard(schematic, {}).document;
        auto findBoardItem = [&](const QString& label) -> const SketchItem* {
            for (const auto& schItem : schematic) {
                if (schItem.label != label) continue;
                for (const auto& boardItem : board) {
                    if (boardItem.sourceId == schItem.id) return &boardItem;
                }
            }
            return nullptr;
        };
        const auto* r1 = findBoardItem(QStringLiteral("R1"));
        const auto* r2 = findBoardItem(QStringLiteral("R2"));
        QVERIFY(r1 && r2);
        const auto* footprint1 = findSymbol(r1->variant);
        const auto* footprint2 = findSymbol(r2->variant);
        QVERIFY(footprint1 && footprint2);
        // R1 pin 1 is on the source rail's net; R2 pin 2 is on the ground net -- different nets.
        const QPointF p1 = symbolToWorld(*r1, footprint1->pins[0]);
        const QPointF p2 = symbolToWorld(*r2, footprint2->pins[1]);
        const QPointF d = p2 - p1;
        QVERIFY(!d.isNull());
        const QPointF perp(-d.y(), d.x());
        const QPointF crossing = (p1 + p2) / 2.0 + perp * 0.25;

        auto crossingBoard = [&](BoardLayer secondLayer) {
            SketchDocument withTracks = board;
            SketchItem trackA;
            trackA.kind = SketchItem::Kind::Wire;
            trackA.layer = BoardLayer::TopCopper;
            trackA.points = {p1, p1 + (crossing - p1) * 2.0};
            SketchItem trackB;
            trackB.kind = SketchItem::Kind::Wire;
            trackB.layer = secondLayer;
            trackB.points = {p2, p2 + (crossing - p2) * 2.0};
            withTracks << trackA << trackB;
            return withTracks;
        };

        // Same layer: the crossing physically joins R1 pin 1 to R2 pin 2 -- a real short.
        QVERIFY(boardGuidance(schematic, crossingBoard(BoardLayer::TopCopper)).errors.join(" ").contains("short"));
        // Different layers: the tracks cross geometrically but do not conduct -- no short.
        QVERIFY(!boardGuidance(schematic, crossingBoard(BoardLayer::BottomCopper)).errors.join(" ").contains("short"));
    }
    void actualWorkflowReportsAndUndoUpdatesGuidance() {
        QWidget host;
        QMenu menu;
        DesignCanvas schematic(Workspace::Schematic), board(Workspace::Board);
        QHash<QString, QPointer<QTextEdit>> reports;
        CircuitWorkflow flow(&host, &menu, &schematic, &board,
            [&](const QString& id, const QString&, QWidget* widget) {
                widget->setParent(&host);
                reports[id] = qobject_cast<QTextEdit*>(widget);
            }, [] { return true; }, [] {});
        flow.loadExample();
        QCOMPARE(schematic.document().size(), 7);
        flow.showNetlist();
        auto* netlist = reports["hatteda.tool.netlist"].data();
        QVERIFY(netlist);
        QVERIFY(netlist->toPlainText().contains("R1"));
        flow.showNetlist();
        QCOMPARE(reports["hatteda.tool.netlist"].data(), netlist);
        flow.updateBoard();
        QCOMPARE(board.document().size(), 3);
        QCOMPARE(board.airwires().size(), 3);
        flow.updateBoard();
        QCOMPARE(board.undoStack()->count(), 1);
        board.undoStack()->undo();
        QVERIFY(board.document().isEmpty());
        QVERIFY(board.airwires().isEmpty());
        board.undoStack()->redo();
        QCOMPARE(board.airwires().size(), 3);
        flow.runDc();
        auto* sim = reports["hatteda.tool.dc-results"].data();
        QVERIFY(sim);
        QTRY_VERIFY_WITH_TIMEOUT(sim->toPlainText().contains("2.5"), 5000);
        flow.runDc();
        QTRY_VERIFY_WITH_TIMEOUT(sim->toPlainText().contains("2.5"), 5000);
        schematic.undoStack()->undo();
        QVERIFY(sim->toPlainText().contains("out of date"));
    }
    void boardPartsFollowSchematicPlacement() {
        auto schematic = dcDividerExample();
        auto waiting = unplacedBoardParts(schematic, {});
        QVERIFY(waiting.problems.isEmpty());
        QCOMPARE(waiting.parts.size(), 3);
        QCOMPARE(waiting.parts[0].label, QString("R1"));
        QCOMPARE(waiting.parts[1].label, QString("R2"));
        QCOMPARE(waiting.parts[2].label, QString("V1"));
        QCOMPARE(waiting.parts[0].sourceId, schematic[1].id);
        QCOMPARE(waiting.parts[0].variant, QString("board.r0603"));

        // A placed footprint leaves the list; an excluded component never enters it.
        SketchDocument board = {waiting.parts[0]};
        schematic[2].excludeFromBoard = true;
        waiting = unplacedBoardParts(schematic, board);
        QCOMPARE(waiting.parts.size(), 1);
        QCOMPARE(waiting.parts[0].label, QString("V1"));
        const auto transfer = transferToBoard(schematic, board);
        QVERIFY2(transfer.errors.isEmpty(), qPrintable(transfer.errors.join("; ")));
        QCOMPARE(transfer.added, 1);
        const auto guide = boardGuidance(schematic, transfer.document);
        QVERIFY(!guide.errors.join(" ").contains("R2"));

        // Without a footprint the component is reported instead of listed.
        schematic[1].footprint.clear();
        waiting = unplacedBoardParts(schematic, {});
        QCOMPARE(waiting.parts.size(), 1);
        QCOMPARE(waiting.problems.size(), 1);
    }
    void autoPlacerKeepsPartsInsideOutlineWithoutOverlap() {
        SketchItem outline;
        outline.kind = SketchItem::Kind::Polyline;
        outline.variant = BoardOutlineVariant;
        outline.closed = true;
        outline.points = {{0, 0}, {40, 0}, {40, 30}, {0, 30}};
        SketchItem existing;
        existing.kind = SketchItem::Kind::Symbol;
        existing.variant = "board.dip8";
        existing.points = {{8, 8}};
        const SketchDocument board = {outline, existing};
        SketchDocument parts;
        for (int i = 0; i < 6; ++i) {
            SketchItem part;
            part.kind = SketchItem::Kind::Symbol;
            part.variant = i % 2 ? "board.soic8" : "board.r0603";
            part.label = QString("U%1").arg(i + 1);
            parts.append(part);
        }
        const auto placed = autoPlaceParts(board, parts, 1.27);
        QCOMPARE(placed.size(), board.size() + parts.size());
        QVector<QRectF> bounds;
        for (int i = 1; i < placed.size(); ++i) bounds.append(itemBounds(placed[i]));
        for (int i = 0; i < bounds.size(); ++i) {
            QVERIFY2(QRectF(0, 0, 40, 30).contains(bounds[i]), qPrintable(placed[i + 1].label));
            for (int j = i + 1; j < bounds.size(); ++j) QVERIFY(!bounds[i].intersects(bounds[j]));
        }
        for (int i = 2; i < placed.size(); ++i) {
            const QPointF origin = placed[i].points.first();
            QVERIFY(std::abs(origin.x() / 1.27 - std::round(origin.x() / 1.27)) < 1e-6);
        }
    }
    void autoPlacerUsesOrdinaryBoardEdgeGeometry() {
        SketchItem outline;
        outline.kind = SketchItem::Kind::Rectangle;
        outline.layer = BoardLayer::BoardEdge;
        outline.points = {{10, 20}, {50, 45}};
        SketchItem part;
        part.kind = SketchItem::Kind::Symbol;
        part.variant = "board.dip8";
        part.label = "U1";

        const SketchDocument placed = autoPlaceParts({outline}, {part}, 1.27, 2.0);
        QCOMPARE(placed.size(), 2);
        const QRectF bounds = itemBounds(placed.last());
        QVERIFY(QRectF(10, 20, 40, 25).contains(bounds.adjusted(-2, -2, 2, 2)));
    }
    void autoPlacerNeverEscapesNonRectangularOutline() {
        SketchItem outline;
        outline.kind = SketchItem::Kind::Polyline;
        outline.layer = BoardLayer::BoardEdge;
        outline.closed = true;
        outline.points = {{0, 0}, {40, 0}, {40, 12}, {18, 12}, {18, 35}, {0, 35}};
        SketchDocument parts;
        for (int i = 0; i < 4; ++i) {
            SketchItem part;
            part.kind = SketchItem::Kind::Symbol;
            part.variant = "board.r0603";
            part.label = QString("R%1").arg(i + 1);
            parts.append(part);
        }

        const SketchDocument placed = autoPlaceParts({outline}, parts, 1.0, 1.0);
        QCOMPARE(placed.size(), 5);
        QPolygonF polygon(outline.points);
        for (int i = 1; i < placed.size(); ++i) {
            const QRectF bounds = itemBounds(placed[i]).adjusted(-1, -1, 1, 1);
            QVERIFY(polygon.containsPoint(bounds.topLeft(), Qt::OddEvenFill));
            QVERIFY(polygon.containsPoint(bounds.topRight(), Qt::OddEvenFill));
            QVERIFY(polygon.containsPoint(bounds.bottomLeft(), Qt::OddEvenFill));
            QVERIFY(polygon.containsPoint(bounds.bottomRight(), Qt::OddEvenFill));
        }
    }
    void netlistTextListsPartsAndNets() {
        const auto text = netlistText(dcDividerExample());
        QVERIFY(text.contains("*PARTS"));
        QVERIFY(text.contains("R1 schematic.resistor 1k board.r0603"));
        QVERIFY(text.contains("*NETS"));
        QVERIFY(text.contains(QRegularExpression("\\n0: .*V1\\.2")));
        QStringList errors;
        auto broken = dcDividerExample();
        broken[1].label = "V1";
        QVERIFY(netlistText(broken, &errors).isEmpty());
        QVERIFY(!errors.isEmpty());
    }
    void autoPlacerDialogPlacesPartsInOneStep() {
        MainWindow window;
        window.resize(1440, 900);
        window.show();
        QTimer::singleShot(0, [] {
            if (auto* dialog = qobject_cast<QDialog*>(QApplication::activeModalWidget())) dialog->accept();
        });
        window.createNewProject();
        auto* flow = window.findChild<CircuitWorkflow*>();
        flow->loadExample();
        window.showKayraWorkspace();
        auto* board = window.activeCanvas();
        SketchItem outline;
        outline.kind = SketchItem::Kind::Polyline;
        outline.variant = BoardOutlineVariant;
        outline.closed = true;
        outline.points = {{0, 0}, {50, 0}, {50, 40}, {0, 40}};
        board->applyDocumentEdit("outline", {outline});

        QTimer::singleShot(0, [] {
            auto* dialog = qobject_cast<QDialog*>(QApplication::activeModalWidget());
            QVERIFY(dialog);
            QCOMPARE(dialog->objectName(), QString("AutoPlacerDialog"));
            dialog->findChild<QDoubleSpinBox*>("AutoPlacerGrid")->setValue(2.54);
            dialog->findChild<QDoubleSpinBox*>("AutoPlacerSpacing")->setValue(5.0);
            dialog->findChild<QDialogButtonBox*>()->button(QDialogButtonBox::Ok)->click();
        });
        window.findChild<QAction*>("hatteda.action.auto-place")->trigger();
        QCOMPARE(board->document().size(), 4);
        QCOMPARE(board->undoStack()->count(), 2);
        for (int i = 1; i < 4; ++i) {
            QVERIFY(QRectF(0, 0, 50, 40).contains(itemBounds(board->document()[i])));
            QVERIFY(!board->document()[i].sourceId.isEmpty());
        }
        QCOMPARE(QSettings().value("pcb/autoPlacer/spacing").toDouble(), 5.0);
        QCOMPARE(board->airwires().size(), 3);
        QCOMPARE(flow->autoPlace(1.27, 2.54), 0);
        QCOMPARE(board->undoStack()->count(), 2);
    }
    // Issue #49: Circuit > Auto Router... no longer opens its own settings dialog; it opens the
    // Design Rule Manager with the Autorouter tab active, so routing settings live alongside the
    // rules that constrain them.
    void autoRouterOpensDesignRulesOnAutorouterTab() {
        MainWindow window;
        window.resize(1200, 800);
        window.show();
        QTimer::singleShot(0, [] {
            if (auto* dialog = qobject_cast<QDialog*>(QApplication::activeModalWidget())) dialog->accept();
        });
        window.createNewProject();
        auto* action = window.findChild<QAction*>("hatteda.action.auto-route");
        QVERIFY(action);
        QVERIFY(action->text().contains(QStringLiteral("Auto Router")));

        QTimer::singleShot(0, [] {
            auto* dialog = qobject_cast<QDialog*>(QApplication::activeModalWidget());
            QVERIFY(dialog);
            QCOMPARE(dialog->objectName(), QStringLiteral("DesignRuleManagerDialog"));
            auto* tabs = dialog->findChild<QTabWidget*>("RuleTabs");
            QVERIFY(tabs);
            QCOMPARE(tabs->currentWidget()->objectName(), QStringLiteral("DesignRulesAutorouterTab"));
            QVERIFY(dialog->findChild<QSpinBox*>("AutorouterPasses"));
            QVERIFY(dialog->findChild<QSpinBox*>("AutorouterTimeout"));
            QVERIFY(dialog->findChild<QSpinBox*>("AutorouterThreads"));
            QVERIFY(dialog->findChild<QComboBox*>("AutorouterUpdateStrategy"));
            QVERIFY(dialog->findChild<QComboBox*>("AutorouterSelectionStrategy"));
            QVERIFY(dialog->findChild<QLabel*>("AutorouterLayers"));
            QVERIFY(dialog->findChild<QPushButton*>("RouteBoard"));
            dialog->reject();
        });
        action->trigger();
    }
    void liveSimulationShowsProbeVoltagesAndFollowsEdits() {
        MainWindow window;
        window.resize(1440, 900);
        window.show();
        auto* start = window.findChild<QAction*>("hatteda.action.simulation-start");
        auto* stop = window.findChild<QAction*>("hatteda.action.simulation-stop");
        QVERIFY(start && stop);
        QVERIFY(!start->isEnabled());
        QTimer::singleShot(0, [] {
            if (auto* dialog = qobject_cast<QDialog*>(QApplication::activeModalWidget())) dialog->accept();
        });
        window.createNewProject();
        QVERIFY(start->isEnabled());
        QVERIFY(!stop->isEnabled());
        bool onCommandBar = false;
        for (auto* button : window.findChildren<QToolButton*>())
            onCommandBar = onCommandBar || button->defaultAction() == start;
        QVERIFY(onCommandBar);

        auto* flow = window.findChild<CircuitWorkflow*>();
        flow->loadExample();
        auto* schematic = window.activeCanvas();
        SketchItem probe;
        probe.kind = SketchItem::Kind::Symbol;
        probe.variant = "schematic.voltage-probe";
        probe.label = "VP1";
        probe.points = {{50.8, 20.32}}; // R1 pin 2, the divider midpoint
        auto document = schematic->document();
        document.append(probe);
        schematic->applyDocumentEdit("probe", document);

        start->trigger();
        QVERIFY(flow->simulationRunning());
        QVERIFY(!start->isEnabled() && stop->isEnabled());
        // Live runs stay on the schematic instead of opening the results workspace.
        QCOMPARE(window.toolWorkspaceCount(), 0);
        QTRY_COMPARE_WITH_TIMEOUT(schematic->annotations().size(), 1, 5000);
        QCOMPARE(schematic->annotations().first().text, QString("2.5 V"));

        auto r2 = schematic->document()[2];
        QCOMPARE(r2.label, QString("R2"));
        r2.value = "3k";
        schematic->editItemProperties(2, r2);
        QTRY_COMPARE_WITH_TIMEOUT(schematic->annotations().value(0).text, QString("3.75 V"), 5000);

        stop->trigger();
        QVERIFY(!flow->simulationRunning());
        QVERIFY(schematic->annotations().isEmpty());
        QVERIFY(start->isEnabled() && !stop->isEnabled());
    }
    void duplicateCreatesNewIdentity() {
        DesignCanvas canvas(Workspace::Schematic);
        const auto document = dcDividerExample();
        canvas.restore({document[1]}, {0});
        canvas.duplicateSelection();
        QCOMPARE(canvas.document().size(), 2);
        QVERIFY(canvas.document()[0].id != canvas.document()[1].id);
        QVERIFY(analyzeSchematic(canvas.document()).errors.isEmpty());
        canvas.undoStack()->undo();
        QCOMPARE(canvas.document().first().id, document[1].id);
    }
    void hostReusesReportsAndShowsBothThemes() {
        MainWindow window;
        window.resize(1440, 900);
        window.show();
        QTimer::singleShot(0, [] {
            if (auto* dialog = qobject_cast<QDialog*>(QApplication::activeModalWidget())) dialog->accept();
        });
        window.createNewProject();
        auto* flow = window.findChild<CircuitWorkflow*>();
        QVERIFY(flow);
        flow->loadExample();
        flow->showNetlist();
        QPointer<QTextEdit> netlist = window.findChild<QTextEdit*>("hatteda.tool.netlist");
        QVERIFY(netlist);
        flow->showNetlist();
        QVERIFY(netlist);
        QCOMPARE(window.toolWorkspaceCount(), 1);
        flow->runDc();
        auto* simulation = window.findChild<QTextEdit*>("hatteda.tool.dc-results");
        QVERIFY(simulation);
        QTRY_VERIFY_WITH_TIMEOUT(simulation->toPlainText().contains("2.5"), 5000);
        flow->runDc();
        QTRY_VERIFY_WITH_TIMEOUT(simulation->toPlainText().contains("2.5"), 5000);
        QCOMPARE(window.toolWorkspaceCount(), 2);
        const QString directory = qEnvironmentVariable("HATT_SCREENSHOT_DIR");
        for (auto mode : {ThemeMode::Dark, ThemeMode::Light}) {
            Theme::apply(*qApp, mode);
            const QString suffix = mode == ThemeMode::Dark ? "dark" : "light";
            auto capture = [&](QString name) {
                QCoreApplication::processEvents();
                if (!directory.isEmpty()) {
                    QVERIFY(QDir().mkpath(directory));
                    QVERIFY(window.grab().save(directory + '/' + name + '-' + suffix + ".png"));
                }
            };
            flow->showNetlist(); capture("netlist");
            window.showMergenWorkspace(); capture("schematic");
            flow->updateBoard(); capture("pcb");
            flow->runDc();
            QTRY_VERIFY_WITH_TIMEOUT(simulation->toPlainText().contains("2.5"), 5000);
            capture("dc");
            const auto rendered = simulation->viewport()->grab().toImage();
            const QColor background = rendered.pixelColor(rendered.width() - 10, rendered.height() - 10);
            QCOMPARE(background.lightness() > 128, mode == ThemeMode::Light);
        }
    }
};
QTEST_MAIN(SketchCircuitTests)
#include "SketchCircuitTests.moc"
